using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using MyBudgetAPI.Models;

namespace MyBudget.DAL.Configuration
{
    internal class IncomeConfiguration : IEntityTypeConfiguration<Income>
    {
        public void Configure(EntityTypeBuilder<Income> builder)
        {
         
            builder.HasKey(i => i.Id);

            // Configure the primary key to be an Identity column auto-generated by the database it happens when we add new user 
            builder.Property(i => i.Id)
                   .ValueGeneratedOnAdd();
         

            builder.Property(i => i.Title)
                .IsRequired()
                .HasMaxLength(100);

            builder.Property(i => i.Amount)
                .HasColumnType("decimal(18,2)");

            builder.Property(i => i.Source)
                .HasMaxLength(100);

            builder.Property(i => i.DateReceived)
                .IsRequired();

            builder.Property(i => i.Note)
                .HasMaxLength(500);

            // Relationship with the User
            builder.HasOne(i => i.User)
                .WithMany() 
                .HasForeignKey(i => i.UserId)
                .OnDelete(DeleteBehavior.Cascade); // This means if a User is deleted, their Incomes are also deleted
        }
    }
}